CREATE TABLE IF NOT EXISTS users (
	id INT(10) AUTO_INCREMENT  NOT NULL,
	Login VARCHAR(50) UNIQUE NOT NULL,
	AccessKey VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;